version: 0.2

env:
  variables:
    TestSuite: "smoke"
    TestUrl: "https://dummyurl.com"
    Environment: "dev"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing pytest
      - pip install pytest

  build:
    commands:
      - echo Running Tests
      - echo "TestSuite=$TestSuite"
      - echo "TestUrl=$TestUrl"
      - echo "Environment=$Environment"
      - pytest test_app.py

artifacts:
  files:
    - "**/*"
