AWSTemplateFormatVersion: "2010-09-09"
Description: S3 Based Deployment Pipeline

Parameters:
  ArtifactBucket:
    Type: String

Resources:
  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: pipeline-demo-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt PipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: S3Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: S3
                Version: 1
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                S3Bucket: !Ref ArtifactBucket
                S3ObjectKey: app.zip
                PollForSourceChanges: true
              RunOrder: 1

        - Name: DevDeploy
          Actions:
            - Name: DummyDeploy
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: test-build-project
              InputArtifacts:
                - Name: SourceOutput
              RunOrder: 1
