AWSTemplateFormatVersion: "2010-09-09"
Description: CodeBuild Projects - CI, Deploy, and Test

Parameters:
  ArtifactBucket:
    Type: String

Resources:
  #################################################
  # IAM Role
  #################################################

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: codebuild-demo-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                  - logs:*
                Resource: "*"

  #################################################
  # 1️⃣ CI Build (Manual trigger)
  #################################################

  CiPackageBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: app-ci-build
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: ARTIFACT_BUCKET
            Value: !Ref ArtifactBucket
      Source:
        Type: GITHUB
        Location: https://github.com/DipanjanRay/codepipeline-test-demo.git
        BuildSpec: buildspec-package.yml

  #################################################
  # 2️⃣ Dummy Deploy Build (Pipeline stage)
  #################################################

  DeployBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: app-deploy-build
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            build:
              commands:
                - echo "Simulating deployment..."
                - echo "Listing pipeline artifact content:"
                - ls -la

  #################################################
  # 3️⃣ Test Build (Pipeline stage)
  #################################################

  TestAutomationBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: app-test-build
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: Environment
            Value: dev
          - Name: TestSuite
            Value: smoke
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml
