AWSTemplateFormatVersion: "2010-09-09"
Description: Demo CodeBuild Projects

Parameters:
  GitHubRepo:
    Type: String
    Default: https://github.com/DipanjanRay/codepipeline-test-demo.git

  ArtifactBucket:
    Type: String

  BranchName:
    Type: String
    Default: main

  TestSuite:
    Type: String
    Default: smoke

  EnvironmentName:
    Type: String
    Default: dev

Resources:
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: demo-codebuild-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  # ------------------------------------
  # Packaging Build (unchanged)
  # ------------------------------------
  PackageBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: package-build-project
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
      Source:
        Type: GITHUB
        Location: !Ref GitHubRepo
        BuildSpec: buildspec-package.yml

  # ------------------------------------
  # Single Test CodeBuild (GitHub Source)
  # ------------------------------------
  DemoTestBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: demo-test-build
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: Environment
            Value: !Ref EnvironmentName
          - Name: TestSuite
            Value: !Ref TestSuite
      Source:
        Type: GITHUB
        Location: !Ref GitHubRepo
        GitCloneDepth: 1
        ReportBuildStatus: true
        SourceVersion: !Ref BranchName
